name: PyProteinsGPU
channels:
   - nvidia
   - pytorch
   - anaconda
   - conda-forge
   - numba
dependencies:
   - python=3.7
   - numpy=1.19
   - scipy=1.5
   - pandas=1.1
   - scikit-learn>=1.0
   - pytorch==1.8.0
   - cudatoolkit=11.1
   - torchvision==0.9.0
   - torchaudio==0.8.0
   - statsmodels
   - python-dotenv
   - pip
   - pyyaml
   - jupyterlab
   - matplotlib
   - openpyxl
   - seaborn
